name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1.1.1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "We that that this is your first issue here on the tracker. Thank you for reaching out we will look into your issue as soon as possible."
        pr-message: "Thank you for submitting a pull request we will review the changes and deciede if the changes are apropriate."
